apiVersion: v2
name: snyk-monitor
description: A Helm chart for Snyk Monitor to scan Kubernetes workloads
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: kubernetes-monitor
    version: 1.0.0
    repository: https://snyk.github.io/kubernetes-monitor


resource "sentry_monitor" "daily_backup" {
  organization    = "your-org-slug"           # e.g., "acme-corp"
  project        = sentry_project.api.id     # Reference an existing project
  name           = "Daily Backup Job"
  schedule_type  = "crontab"                 # or "interval"
  schedule       = "0 0 * * *"               # Runs at midnight daily
  checkin_margin = 5                         # Grace period (minutes)
  max_runtime    = 30                        # Timeout (minutes)
  timezone      = "UTC"                      # Optional
}


terraform import sentry_rule.example_alert org-slug:project-slug:alert-id
terraform import sentry_rule.example_alert my-org:my-project:12345


curl -H "Authorization: Bearer YOUR_API_TOKEN" \
  "https://sentry.io/api/0/organizations/{org-slug}/monitors/" | jq

terraform import sentry_monitor.example org-slug:project-slug:monitor-id




# Create the IAM service account
resource "aws_iam_user" "dynamodb_manager" {
  name = "dynamodb-manager-sa"
}

# Create access keys for the service account
resource "aws_iam_access_key" "dynamodb_manager_key" {
  user = aws_iam_user.dynamodb_manager.name
}

# Minimal policy for DynamoDB table management
resource "aws_iam_policy" "dynamodb_table_management" {
  name        = "DynamoDBTableManagement"
  description = "Policy for creating and managing DynamoDB tables"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "DynamoDBTableOperations",
        Effect = "Allow",
        Action = [
          "dynamodb:CreateTable",
          "dynamodb:UpdateTable",
          "dynamodb:DeleteTable",
          "dynamodb:DescribeTable",
          "dynamodb:ListTables",
          "dynamodb:TagResource",
          "dynamodb:ListTagsOfResource"
        ],
        Resource = "*" # replace with specific  of Table
      }
    ]
  })
}

# Attach the policy to the service account
resource "aws_iam_user_policy_attachment" "dynamodb_manager_attach" {
  user       = aws_iam_user.dynamodb_manager.name
  policy_arn = aws_iam_policy.dynamodb_table_management.arn
}

# Create a role that the service account can assume
resource "aws_iam_role" "dynamodb_assume_role" {
  name = "DynamoDBTableManagerRole"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          AWS = aws_iam_user.dynamodb_manager.arn
        }
      },
    ]
  })
}

# Attach the same policy to the assume role
resource "aws_iam_role_policy_attachment" "dynamodb_role_attach" {
  role       = aws_iam_role.dynamodb_assume_role.name
  policy_arn = aws_iam_policy.dynamodb_table_management.arn
}

#  DynamoDB Table Creation
# --------------------------

resource "aws_dynamodb_table" "clumio_table" {
  name           = "ClumioAlerts"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "id"

  attribute {
    name = "id"
    type = "S"
  }

  # Enable point-in-time recovery 
  point_in_time_recovery {
    enabled = true
  }
}

# 3. Outputs
# ----------

# output "service_account_access_key" {
#   value     = aws_iam_access_key.dynamodb_manager_key.id
#   sensitive = true
# }

# output "service_account_secret_key" {
#   value     = aws_iam_access_key.dynamodb_manager_key.secret
#   sensitive = true
# }

output "assume_role_arn" {
  value = aws_iam_role.dynamodb_assume_role.arn
}

output "dynamodb_table_name" {
  value = aws_dynamodb_table.example_table.name
}

output "dynamodb_table_arn" {
  value = aws_dynamodb_table.example_table.arn
}


Resource = [
          aws_dynamodb_table.example_table.arn,
          "${aws_dynamodb_table.example_table.arn}/index/*" # For any indexes
        ]


You are saying that PR is not importable but I have imported two projects in local from sentry using these command and imported teams as well. Can I import all the projects and teams one by one?
