apiVersion: v2
name: snyk-monitor
description: A Helm chart for Snyk Monitor to scan Kubernetes workloads
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: kubernetes-monitor
    version: 1.0.0
    repository: https://snyk.github.io/kubernetes-monitor
